# This is a basic workflow to help you get started with Actions

name: DeployStagingServer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - staging
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_STAGING_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd ChessOnGolem
            git fetch --all
            git reset --hard origin/staging
            git checkout staging
            cd chess
            yarn install
            pm2 reload all
          
